image: node:16.13.1-buster

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
    - pnpm install
    - npm run build
    - mv dist/ client-admin/
  artifacts:
    paths:
      - client-admin
    expire_in: 1 week
